#' Write a bibliography of the R packages used in a project
#'
#' Write a BibTeX file with an entry for every R package the project uses
#' (keys \code{R-<package>}, as \code{knitr::write_bib()}), plus R itself
#' (\code{R-base}). Packages are found with [project_packages()]; entries are
#' generated by \code{xfun::pkg_bib()}, one package at a time, so a package
#' whose \code{citation()} fails does not stop the others.
#'
#' Calling \code{citation()} is the slow part, so it is skipped when the file
#' already has an entry for every package, at the installed version. The file
#' is only rewritten when its content changes. Packages whose
#' \code{citation()} fails (e.g. no \code{Authors@R} in their DESCRIPTION) are
#' listed in a \code{\% citation() failed} comment at the top of the file, and
#' retried when their version changes.
#'
#' Call it once (e.g. from the console) to create the file; [knit()] then
#' keeps it up to date on every knit (see the \code{bib_packages} option in
#' [opts_knit]). knitrmini never creates the file on its own.
#'
#' knitrmini only writes files it created: they start with
#' \code{\% generated by knitrmini}, and [knit()] updates every \code{.bib}
#' next to the document that starts with that line, whatever its name. Any
#' other existing file is left alone (an error here, skipped by [knit()])
#' unless \code{force = TRUE}.
#'
#' In an renv project (a \code{renv.lock} in \code{path} or above), packages
#' and their versions are looked up in the project's renv library even when
#' renv is not active in the session, e.g. when knitting from a subfolder,
#' where the project's \code{.Rprofile} is not run. Packages not in that
#' library are reported as not installed.
#'
#' @param file Output file, relative to \code{path} unless absolute.
#' @param path Folder of the documents. The project scanned is the nearest
#'   ancestor folder with a \code{.git}, or \code{path} itself.
#' @param packages Package names to use instead of scanning the project.
#' @param extra Package names to add to the scanned ones (e.g. packages only
#'   loaded through strings, like \code{future.packages = "pkg"}).
#' @param exclude Package names to leave out.
#' @param cite_r Include R itself (\code{R-base}).
#' @param force Regenerate all entries even if the file is up to date, and
#'   overwrite a file that knitrmini did not write.
#' @param quiet Suppress messages.
#' @return Invisibly, a list with the \code{file} path, the \code{packages}
#'   written, whether the file \code{changed}, the packages that are
#'   \code{missing} (not installed) or \code{failed} (\code{citation()} error),
#'   and the \code{library} used (\code{NULL} for the session's library paths).
#' @seealso [project_packages()]
#' @export
#'
#' @examples
#' f <- tempfile(fileext = ".bib")
#' write_pkg_bib(f, packages = c("base", "xfun"))
#' readLines(f)
#' unlink(f)
write_pkg_bib <- function(file = "packages.bib", path = ".", packages = NULL,
                          extra = NULL, exclude = NULL, cite_r = TRUE,
                          force = FALSE, quiet = FALSE) {
  path <- normalizePath(path, mustWork = TRUE)
  if (!is_abs_path(file)) file <- file.path(path, file)
  if (!force && pkg_bib_owner(file) == "other") {
    stop(basename(file), " was not written by knitrmini; not overwriting it. ",
      "Use force = TRUE to overwrite it, or choose another file name.", call. = FALSE)
  }

  pkgs <- unique(c(packages %n% project_packages(path), extra, if (cite_r) "base"))
  pkgs <- setdiff(pkgs, c(exclude, setdiff(xfun::base_pkgs(), "base")))
  if (!cite_r) pkgs <- setdiff(pkgs, "base")
  lib <- pkg_library(path)
  installed <- vapply(pkgs, function(p) {
    nzchar(system.file(package = p, lib.loc = lib))
  }, logical(1))
  res <- list(
    file = file, packages = sort(pkgs[installed]), changed = FALSE,
    missing = sort(pkgs[!installed]), failed = character(), library = lib
  )

  current <- if (!force && file.exists(file)) pkg_bib_current(file, res$packages, lib)
  if (!is.null(current)) {
    res$failed <- current
    res$packages <- setdiff(res$packages, current)
  } else {
    lines <- character()
    for (p in res$packages) {
      bib <- tryCatch(
        suppressMessages(xfun::pkg_bib(p, file = NULL, lib.loc = lib)),
        error = function(e) NULL
      )
      if (is.null(bib)) {
        res$failed <- c(res$failed, p)
      } else {
        lines <- c(lines, unlist(bib, use.names = FALSE))
      }
    }
    res$packages <- setdiff(res$packages, res$failed)
    # failed packages are remembered (with their version) so they are only
    # retried when they change
    failed <- if (length(res$failed)) {
      paste("% citation() failed:", res$failed, pkg_version(res$failed, lib),
        pkg_desc_sig(res$failed, lib))
    }
    content <- paste(c(pkg_bib_marker, failed, "", lines), collapse = "\n")
    old <- if (file.exists(file)) paste(xfun::read_utf8(file), collapse = "\n")
    if (!identical(old, content)) {
      xfun::write_utf8(content, file)
      res$changed <- TRUE
    }
  }

  if (!quiet) {
    if (!is.null(lib)) message("Using the renv library ", lib[1])
    message(
      length(res$packages), " package entries -> ", basename(file),
      if (!res$changed) " (unchanged)"
    )
    if (length(res$missing)) {
      message("Not installed: ", paste(res$missing, collapse = ", "))
    }
    if (length(res$failed)) {
      message("citation() failed: ", paste(res$failed, collapse = ", "))
    }
  }
  invisible(res)
}

#' First line of every file written by [write_pkg_bib()]
#' @keywords internal
pkg_bib_marker <- "% generated by knitrmini"

#' Who owns a package bibliography
#'
#' @param file Path to the file.
#' @return \code{"absent"}, \code{"empty"}, \code{"ours"} (first line is the
#'   knitrmini marker) or \code{"other"}. Only \code{"ours"} is kept up to date
#'   by [knit()]; [write_pkg_bib()] writes \code{"absent"} and \code{"empty"}
#'   files, and \code{"other"} only with \code{force = TRUE}.
#' @keywords internal
pkg_bib_owner <- function(file) {
  if (!file.exists(file)) return("absent")
  first <- readLines(file, n = 1, warn = FALSE)
  if (!length(first)) return("empty")
  if (identical(first, pkg_bib_marker)) "ours" else "other"
}

#' Refresh the package bibliographies next to a knitted document
#'
#' Called by [knit()]. Every \code{.bib} in \code{dir} written by
#' [write_pkg_bib()] (first line \code{\% generated by knitrmini}) is brought
#' up to date, whatever its name. Nothing is created, and other files are
#' left alone. Turned off with \code{opts_knit$set(bib_packages = FALSE)}.
#' Errors become warnings.
#'
#' @param dir Folder of the knitted document.
#' @param quiet Suppress messages.
#' @keywords internal
update_pkg_bib <- function(dir, quiet = FALSE) {
  if (!isTRUE(opts_knit$get("bib_packages"))) return(invisible())
  for (f in list.files(dir, "\\.bib$", full.names = TRUE)) {
    if (pkg_bib_owner(f) != "ours") next
    tryCatch(
      write_pkg_bib(f, path = dir, quiet = quiet),
      error = function(e) {
        warning("Could not update ", basename(f), ": ", conditionMessage(e), call. = FALSE)
      }
    )
  }
  invisible()
}

#' Installed versions of packages
#'
#' @param pkgs Package names.
#' @param lib Library paths (\code{NULL} for the session's).
#' @return Character vector of versions.
#' @keywords internal
pkg_version <- function(pkgs, lib = NULL) {
  vapply(pkgs, function(p) {
    as.character(utils::packageDescription(p, lib.loc = lib, fields = "Version"))
  }, character(1), USE.NAMES = FALSE)
}

#' Nearest folder at or above a path that contains a file
#'
#' @param path Starting folder.
#' @param name File or folder name to look for.
#' @return The folder, or \code{NULL}.
#' @keywords internal
find_up <- function(path, name) {
  dir <- normalizePath(path, mustWork = TRUE)
  repeat {
    if (file.exists(file.path(dir, name))) return(dir)
    if (dirname(dir) == dir) return(NULL)
    dir <- dirname(dir)
  }
}

#' Library to look packages up in
#'
#' In an renv project that is not active in this session, the project's renv
#' library (plus R's own library, for base and recommended packages).
#'
#' @param path Folder in the project.
#' @return Library paths, or \code{NULL} for the session's library paths.
#' @keywords internal
pkg_library <- function(path) {
  root <- find_up(path, "renv.lock")
  if (is.null(root)) return(NULL)
  active <- Sys.getenv("RENV_PROJECT")
  if (nzchar(active) && identical(normalizePath(active, mustWork = FALSE), root)) {
    return(NULL)
  }
  lib <- renv_project_library(root)
  if (is.null(lib)) {
    warning("renv.lock found in ", root, " but no renv library for R ",
      getRversion(), "; using the session's library paths", call. = FALSE)
    return(NULL)
  }
  c(lib, .Library)
}

#' Library folder of an renv project
#'
#' Asks renv when it is installed (this honours \code{RENV_PATHS_RENV},
#' \code{RENV_PATHS_LIBRARY} and profiles), and otherwise looks for the
#' standard layouts, \code{<renv>/library/<platform>/R-<x.y>/<arch>} and
#' \code{<renv>/library/R-<x.y>/<arch>}, where \code{<renv>} is
#' \code{RENV_PATHS_RENV}, \code{renv} or \code{.renv}.
#'
#' @param root Project folder (with \code{renv.lock}).
#' @return The library folder, or \code{NULL} if none exists.
#' @keywords internal
renv_project_library <- function(root) {
  if (requireNamespace("renv", quietly = TRUE)) {
    lib <- tryCatch(renv::paths$library(project = root), error = function(e) NULL)
    if (length(lib) == 1 && dir.exists(lib)) return(lib)
  }
  r_ver <- paste0("R-", getRversion()$major, ".", getRversion()$minor)
  libs <- character()
  for (d in renv_dirs()) {
    libs <- c(libs, Sys.glob(c(
      file.path(root, d, "library", "*", r_ver, "*"),
      file.path(root, d, "library", r_ver, "*")
    )))
  }
  libs <- libs[dir.exists(libs)]
  if (length(libs)) libs[1]
}

#' Names of renv project folders
#'
#' @return \code{RENV_PATHS_RENV} (if set and relative), \code{renv} and
#'   \code{.renv}.
#' @keywords internal
renv_dirs <- function() {
  custom <- Sys.getenv("RENV_PATHS_RENV")
  custom <- if (nzchar(custom) && !is_abs_path(custom)) custom
  unique(c(custom, "renv", ".renv"))
}

#' Short checksums of installed packages' DESCRIPTION files
#'
#' @param pkgs Package names.
#' @param lib Library paths (\code{NULL} for the session's).
#' @return First 8 characters of each DESCRIPTION's md5 (\code{NA} if missing).
#' @keywords internal
pkg_desc_sig <- function(pkgs, lib = NULL) {
  vapply(pkgs, function(p) {
    f <- system.file("DESCRIPTION", package = p, lib.loc = lib)
    if (nzchar(f)) substr(unname(tools::md5sum(f)), 1, 8) else NA_character_
  }, character(1), USE.NAMES = FALSE)
}

#' Does a package bibliography have every package at its installed version?
#'
#' @param file Path to the \code{.bib} written by [write_pkg_bib()].
#' @param pkgs Installed package names it should cover.
#' @param lib Library paths (\code{NULL} for the session's).
#' @return \code{NULL} if the file must be regenerated; otherwise the packages
#'   recorded as failed (possibly none). The file is current when every package
#'   has an \code{R-<pkg>} entry or a \code{citation() failed} line, with no
#'   others, the recorded versions match the installed ones, and the
#'   DESCRIPTION of each failed package is unchanged (so a fixed package is
#'   retried even at the same version).
#' @keywords internal
pkg_bib_current <- function(file, pkgs, lib = NULL) {
  lines <- xfun::read_utf8(file)
  keys <- character()
  versions <- character()
  failed <- character()
  for (l in lines) {
    f <- regmatches(l, regexec("^% citation\\(\\) failed: (\\S+) (\\S+)(?: (\\S+))?", l))[[1]]
    if (length(f)) {
      if (!identical(f[4], pkg_desc_sig(f[2], lib))) return(NULL)
      failed <- c(failed, f[2])
      versions[f[2]] <- f[3]
      next
    }
    k <- regmatches(l, regexec("^@\\w+\\{R-([^,]+),", l))[[1]]
    if (length(k)) {
      keys <- c(keys, k[2])
      next
    }
    v <- regmatches(l, regexec("R package version ([^ },]+)", l))[[1]]
    if (length(v) && length(keys)) versions[keys[length(keys)]] <- v[2]
  }
  if (!setequal(c(keys, failed), pkgs)) return(NULL)
  p <- intersect(names(versions), pkgs)
  if (!identical(unname(versions[p]), pkg_version(p, lib))) return(NULL)
  failed
}

#' Find the R packages used in a project
#'
#' Parse the R code of a project and list the packages it uses through
#' \code{library()}, \code{require()}, \code{requireNamespace()},
#' \code{loadNamespace()}, \code{pacman::p_load()}, \code{pkg::f} and
#' \code{pkg:::f}.
#'
#' The project is the nearest ancestor folder of \code{path} with a
#' \code{.git}; its files are listed with \code{git ls-files}, so ignored files
#' are skipped. Without git, \code{path} is searched recursively, skipping
#' hidden folders. renv (\code{renv/}, \code{.renv/}) and \code{packrat/}
#' folders are always skipped. Code is read from
#' \code{.R} files, the chunks of \code{.Rnw} files, and the R chunks of
#' \code{.Rmd} and \code{.qmd} files. Code that does not parse is skipped with
#' a warning.
#'
#' @param path Folder in the project.
#' @return Sorted, unique package names (base packages included).
#' @seealso [write_pkg_bib()]
#' @export
#'
#' @examples
#' d <- tempfile()
#' dir.create(d)
#' writeLines(c("library(stats)", "x <- xfun::file_ext('a.R')"), file.path(d, "a.R"))
#' project_packages(d)
#' unlink(d, recursive = TRUE)
project_packages <- function(path = ".") {
  pkgs <- character()
  for (f in project_files(path)) {
    for (code in r_code_blocks(f)) {
      exprs <- tryCatch(parse(text = code, keep.source = FALSE), error = function(e) {
        warning("Could not parse R code in ", f, ": ", conditionMessage(e), call. = FALSE)
        NULL
      })
      pkgs <- c(pkgs, packages_in_exprs(exprs))
    }
  }
  pkgs <- unique(pkgs[grepl("^[A-Za-z][A-Za-z0-9.]*[A-Za-z0-9]$", pkgs)])
  sort(pkgs)
}

#' R, Rnw, Rmd and qmd files of the project containing a folder
#'
#' @param path Folder in the project.
#' @return Absolute paths.
#' @keywords internal
project_files <- function(path) {
  path <- normalizePath(path, mustWork = TRUE)
  pattern <- "\\.([Rr]|[Rr]nw|[Rr]md|[Qq]md)$"
  skip <- paste0("(^|/)(", paste(gsub(".", "\\.", c(renv_dirs(), "packrat"), fixed = TRUE),
    collapse = "|"), ")/")
  root <- find_up(path, ".git")
  if (!is.null(root) && nzchar(Sys.which("git"))) {
    files <- tryCatch(
      suppressWarnings(system2(
        "git", c("-C", shQuote(root), "-c", "core.quotePath=false", "ls-files",
          "--cached", "--others", "--exclude-standard"),
        stdout = TRUE, stderr = FALSE
      )),
      error = function(e) NULL
    )
    if (!is.null(files) && is.null(attr(files, "status"))) {
      files <- files[grepl(pattern, files) & !grepl(skip, files)]
      files <- file.path(root, files)
      return(files[file.exists(files)])
    }
  }
  files <- list.files(path, pattern, recursive = TRUE)
  files <- files[!grepl(skip, files) & !grepl("(^|/)\\.[^/]*/", files)]
  file.path(path, files)
}

#' Blocks of R code in a file
#'
#' @param file Path to an \code{.R}, \code{.Rnw}, \code{.Rmd} or \code{.qmd}.
#' @return A list of character vectors: the whole file for \code{.R}, one
#'   element per R chunk otherwise.
#' @keywords internal
r_code_blocks <- function(file) {
  lines <- xfun::read_utf8(file)
  ext <- tolower(xfun::file_ext(file))
  if (ext == "r") return(list(lines))
  if (ext == "rnw") {
    start <- "^\\s*<<.*>>=\\s*$"
    end <- "^\\s*@\\s*$"
  } else {
    start <- "^\\s*```+\\s*\\{[rR]([ ,}]|$)"
    end <- "^\\s*```+\\s*$"
  }
  blocks <- list()
  cur <- NULL
  for (l in lines) {
    if (is.null(cur)) {
      if (grepl(start, l)) cur <- character()
    } else if (grepl(end, l)) {
      blocks[[length(blocks) + 1]] <- cur
      cur <- NULL
    } else if (!grepl("^\\s*<<[^>]*>>\\s*$", l)) {
      cur <- c(cur, l)
    }
  }
  blocks
}

#' Package names used in parsed R code
#'
#' @param exprs An expression vector (from \code{parse()}), or \code{NULL}.
#' @return Package names, possibly repeated or invalid (filtered later).
#' @keywords internal
packages_in_exprs <- function(exprs) {
  found <- character()
  name_of <- function(a) {
    if (is.name(a)) {
      as.character(a)
    } else if (is.character(a) && length(a) == 1) {
      a
    }
  }
  first_arg <- function(args, name) {
    if (!is.null(args[[name]])) return(args[[name]])
    unnamed <- if (is.null(names(args))) args else args[names(args) == ""]
    if (length(unnamed)) unnamed[[1]]
  }
  walk <- function(e) {
    if (is.call(e)) {
      fn <- e[[1]]
      if (is.name(fn) && as.character(fn) %in% c("::", ":::")) {
        found <<- c(found, name_of(e[[2]]))
        return(invisible())
      }
      fname <- if (is.name(fn)) {
        as.character(fn)
      } else if (is.call(fn) && identical(fn[[1]], as.name("::"))) {
        found <<- c(found, name_of(fn[[2]]))
        as.character(fn[[3]])
      } else {
        walk(fn)
        ""
      }
      args <- as.list(e)[-1]
      char_only <- isTRUE(args$character.only)
      if (fname %in% c("library", "require")) {
        a <- first_arg(args, "package")
        if (!char_only || is.character(a)) found <<- c(found, name_of(a))
      } else if (fname %in% c("requireNamespace", "loadNamespace")) {
        a <- first_arg(args, "package")
        if (is.character(a)) found <<- c(found, a)
      } else if (fname == "p_load") {
        unnamed <- if (is.null(names(args))) args else args[names(args) == ""]
        lapply(unnamed, function(a) {
          if (!char_only || is.character(a)) found <<- c(found, name_of(a))
        })
      }
      lapply(args, function(a) if (!missing(a)) walk(a))
    } else if (is.pairlist(e)) {
      lapply(as.list(e), function(a) if (!missing(a)) walk(a))
    }
    invisible()
  }
  for (i in seq_along(exprs)) walk(exprs[[i]])
  found[nzchar(found)]
}
