#' Remove the auxiliary files of a compilation
#'
#' Remove the files generated when compiling a document (\code{.aux},
#' \code{.log}, \code{.bbl}, \code{.synctex.gz}, ...), keeping the \code{.tex}
#' and \code{.pdf}. Only files that \code{latexmk} recorded as generated by this
#' compilation are removed: those listed in \code{<base>.fdb_latexmk} and
#' \code{<base>.fls}, plus these two bookkeeping files and the SyncTeX file.
#' Unrelated files sharing the base name (e.g. \code{<base>.R} or
#' \code{<base>.bib}) are never touched, and neither are files outside the
#' document's directory, directories (\code{figure/}, \code{cache/}) or the
#' knitrmini label snapshot (\code{<base>-labels.aux}).
#'
#' @param file Path to the \code{.tex} (or \code{.Rnw}) file; only its base
#'   name and directory are used.
#' @param dry_run If \code{TRUE}, only list the files that would be removed.
#' @param quiet Suppress messages.
#' @return Invisibly, the paths of the removed (or, with \code{dry_run}, the
#'   removable) files.
#' @export
#'
#' @examples
#' \dontrun{
#' knit("paper.Rnw")
#' clean_aux("paper.tex", dry_run = TRUE)
#' clean_aux("paper.tex")
#' }
clean_aux <- function(file, dry_run = FALSE, quiet = FALSE) {
  dir <- normalizePath(dirname(file), mustWork = TRUE)
  base <- xfun::sans_ext(basename(file))
  stem <- file.path(dir, base)
  fdb <- paste0(stem, ".fdb_latexmk")
  fls <- paste0(stem, ".fls")

  if (!file.exists(fdb) && !file.exists(fls)) {
    if (!quiet) message("No latexmk record (", basename(fdb), " or ", basename(fls),
      ") found for ", base, "; nothing removed.")
    return(invisible(character()))
  }

  candidates <- c(
    fdb_generated_files(fdb),
    fls_output_files(fls),
    basename(c(fdb, fls)),
    paste0(base, c(".synctex.gz", ".bbl-SAVE-ERROR"))
  )
  files <- unique(file.path(dir, basename(candidates[is_own_file(candidates, dir, base)])))
  files <- files[file.exists(files) & !dir.exists(files)]

  if (!dry_run) unlink(files)
  if (!quiet) {
    if (length(files)) {
      message(if (dry_run) "Would remove: " else "Removed: ",
        paste(basename(files), collapse = ", "))
    } else {
      message("No auxiliary files to remove for ", base, ".")
    }
  }
  invisible(files)
}

# Files listed in the "(generated)" sections of a .fdb_latexmk file
fdb_generated_files <- function(fdb) {
  if (!file.exists(fdb)) return(character())
  lines <- xfun::read_utf8(fdb)
  section <- ""
  out <- character()
  for (l in lines) {
    if (grepl("^\\s*\\(.*\\)\\s*$", l)) {
      section <- trimws(l)
    } else if (grepl("^\\[", l)) {
      section <- ""
    } else if (section == "(generated)") {
      out <- c(out, regmatches(l, regexpr('(?<=")[^"]+(?=")', l, perl = TRUE)))
    }
  }
  out
}

# Files written by the TeX engine, as listed in a .fls file
fls_output_files <- function(fls) {
  if (!file.exists(fls)) return(character())
  sub("^OUTPUT ", "", grep("^OUTPUT ", xfun::read_utf8(fls), value = TRUE))
}

# Keep only paths directly in `dir`, named `<base>.<ext>`, and never the
# source, the output PDF or the input
is_own_file <- function(paths, dir, base) {
  in_dir <- vapply(paths, function(p) {
    full <- if (is_abs_path(p)) p else file.path(dir, p)
    d <- normalizePath(dirname(full), mustWork = FALSE)
    identical(d, dir)
  }, logical(1), USE.NAMES = FALSE)
  name <- basename(paths)
  own_name <- startsWith(name, paste0(base, ".")) &
    !grepl("\\.(tex|pdf|rnw|snw|r)$", name, ignore.case = TRUE)
  in_dir & own_name
}
